[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ccxt>=4.4.87",
    "flask>=3.1.1",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "ta>=0.11.0",
]
